version: 2

models:
  - name: bridge_country_languages
    description: >
      This model generates a unique mapping of countries and their languages 
      by creating surrogate keys for each combination of `country_code` and `language`.
    columns:
      - name: country_id
        description: Surrogate key for the country.
        tests:
          - not_null
      - name: language_id
        description: Surrogate key for the language.
        tests:
          - not_null

  - name: dim_country
    description: >
      This dimension table contains detailed information about countries, including
      their name, region, subregion, capital, and other metadata.
    columns:
      - name: country_id
        description: Surrogate key for the country.
        tests:
          - not_null
          - unique
      - name: country_name
        description: Official name of the country.
        tests:
          - not_null
      - name: region
        description: The region to which the country belongs.
      - name: subregion
        description: The subregion to which the country belongs.

  - name: dim_currency
    description: >
      This dimension table contains information about currencies, including their
      code, name, and symbol.
    columns:
      - name: currency_id
        description: Surrogate key for the currency.
        tests:
          - not_null
      - name: currency_code
        description: The code of the currency.
        tests:
          - not_null
      - name: currency_name
        description: The name of the currency.
      - name: currency_symbol
        description: The symbol for the currency.

  - name: dim_language
    description: >
      This dimension table contains unique languages spoken in countries.
    columns:
      - name: language_id
        description: Surrogate key for the language.
        tests:
          - not_null
          - unique
      - name: language
        description: The name of the language.
        tests:
          - not_null
          - unique

  - name: fact_country_metric
    description: >
      This fact table combines key metrics about countries, such as population density,
      language diversity, and currency, to facilitate analytical queries.
    columns:
      - name: country_id
        description: Surrogate key for the country.
        tests:
          - not_null
          - relationships:
              to: ref('stg_country')
              field: country_id
      - name: population
        description: Total population of the country.
        tests:
          - not_null
      - name: area
        description: Total area of the country in square kilometers.
      - name: population_density
        description: Population density (population per square kilometer).
      - name: density_category
        description: >
          A categorical representation of population density (Low, Medium, High).
      - name: language_count
        description: Number of languages spoken in the country.
      - name: language_diversity_category
        description: >
          A categorical representation of language diversity 
          (Monolingual, Moderately Multilingual, Highly Multilingual).
      - name: currency_id
        description: Surrogate key for the currency used by the country.
        tests:
          - relationships:
              to: ref('currency_mapping')
              field: currency_id

tests:
  - name: validate_population_density
    description: >
      Validates that population density is greater than zero for all countries
      with a population and area.
    model: fact_country_metric
    test: expression
    condition: "population_density > 0 OR (population IS NULL AND area IS NULL)"
